import { routing } from "@/libs/i18n/routing";

import { Geist, Geist_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import type React from "react";

import { CookiesStorageKeys } from "@/constants/keys";
import { Language } from "@/libs/i18n/type";
import { ReactQueryProvider } from "@/libs/react-query/provider";
import { ThemeProviders } from "@/libs/theme/provider";
import { Theme } from "@/libs/theme/types";
import { ReduxProvider } from "@/store/provider";
import "@/styles/globals.css";
import { Metadata, Viewport } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Demo",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as Language)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages({ locale: locale as Language });

  const cookieStore = await cookies();
  const theme = (cookieStore.get(CookiesStorageKeys.THEME)?.value as Theme) || Theme.LIGHT;

  return (
    <html
      lang={locale}
      className={theme}
      style={{ colorScheme: theme }}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <ReactQueryProvider>
            <NextIntlClientProvider messages={messages}>
              <ThemeProviders theme={theme}>
                <main className="mx-auto">
                  <ToastContainer
                    position="top-right"
                    autoClose={3000}
                    hideProgressBar={false}
                    newestOnTop
                    closeOnClick
                    pauseOnFocusLoss
                    draggable
                    pauseOnHover
                  />
                  {children}
                </main>
              </ThemeProviders>
            </NextIntlClientProvider>
          </ReactQueryProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
